### ISSUE TITLE
Script not detected

### ISSUE THREAD

**Issue by dferber90** [simpleanalytics/gatsby-plugin#3]
I've set up a Gatsby site and I'm using `gatsby-plugin-simple-analytics`. If you go to https://help.workoutscheduler.de/, you can see that the integration code is indeed installed (check the source code and search for `/hello.js`).

Unfortunately, Simple Analytics doesn't seem to detect that the tracking code is installed (as shown in screenshot below).

<img width="1281" alt="Bildschirmfoto 2019-12-31 um 14 19 24" src="https://user-images.githubusercontent.com/1765075/71622808-a470af00-2bd8-11ea-9c90-c6b4e9a5d71c.png">

One possible reason I can think of is that the tracking code gets installed in the `head` area, while the site may check the `body` only.

---

Something else which might be relevant: I've set up Simple Analytics tracking for `workoutscheduler.de` as a different "website". Will the events from "help.workoutscheduler.de" be tracked there as well? Could this be the reason the script on "help.workoutscheduler.de" is not detected?

**Comment by adriaanvanrossum** [comment]
I tested it on my machine and it works:

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/71623806-514e2a80-2bdf-11ea-9b99-4968819f16e2.jpg"></kbd>

This is basically our script that checks for the script:

```js
const body = await request("GET", `${websiteUrl}?cache=${Date.now()}`);
const hasScript = body.indexOf("https://cdn.simpleanalytics.io/hello.js") > -1;

if (hasScript) {
  pool.query(
    "UPDATE websites SET has_script = true WHERE hostname = $1",
    [hostname]
  );
}
```

Could it be caching somewhere? I think your website stats are now working, right?

**Comment by dferber90** [comment]
Yes, I'm happy to report that it's indeed working now. It probably was a caching issue indeed as I'm using Cloudflare & Netlify. I thought I had waited long enough for caching not to be relevant anymore. Thank you a lot for looking into it in such a timely manner.

Hope you have a great NYE tonight 🎆

**Comment by adriaanvanrossum** [comment]
Happy to see it's solved. And NYE was great, thanks! Hope you had a good one too.
