### ISSUE TITLE
Events support

### ISSUE THREAD

**Issue by wassim** [simpleanalytics/gatsby-plugin#4]
I can't get the _sa_event_ function to work. Any ideas?

```
{
    resolve: 'gatsby-plugin-simple-analytics',
    options: {
        // Optional custom domain
        domain: 'sa.mydomain.com',
        eventsGlobal: 'sa',
        events: true,
        trackPageViews: true
    }
}
```

```
const windowGlobal = typeof window !== 'undefined' && window
function () {
    windowGlobal.sa_event("click_button")
}
```

`Error: windowGlobal.sa_event is not a function`

**Comment by adriaanvanrossum** [comment]
What happens if you change `eventsGlobal: 'sa',` to `eventsGlobal: 'sa_event',`?

**Comment by adriaanvanrossum** [comment]
I will close this because of inactivity.

**Comment by ceiphr** [comment]
Hello!

Same issue. Changing `eventsGlobal: 'sa',` to `eventsGlobal: 'sa_event',` didn't fix it for me.
